---
- hosts: backend
  become: true
  tasks:
    - name: Update apt cache (for Debian/Ubuntu systems)
      apt:
        update_cache: yes
      when: ansible_os_family == 'Debian'

    - name: Install Netdata
      package:
        name: netdata
        state: present
      become: true

    - name: Start Netdata service
      service:
        name: netdata
        state: started
        enabled: yes

    - name: Open port 19999 in firewall
      ufw:
        rule: allow
        port: 19999
        proto: tcp
      become: true
      when: ansible_service_mgr == 'systemd'  # Adjust based on the init system used by your target servers
